kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubeinvaders
    chart: {{ template "kubeinvaders.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "jobs"]
  verbs: ["get", "list", "delete", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubeinvaders
    chart: {{ template "kubeinvaders.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubeinvaders.serviceAccountName" $ }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: kubeinvaders-role
  apiGroup: rbac.authorization.k8s.io
