apiVersion: apps/v1
kind: Deployment
metadata:
  name: satellite-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellite-app
  template:
    metadata:
      labels:
        app: satellite-app
    spec:
      containers:
        - name: satellite-app
          image: bashofmann/rancher-demo:1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: COW_COLOR
              value: black
          readinessProbe:
            httpGet:
              port: web
              path: /
