apiVersion: v1
kind: Service
metadata:
  name: satellite-app
  namespace: default
spec:
  type: NodePort
  selector:
    app: satellite-app
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30001
